-- liquibase formatted sql

-- changeset Sergey:1

CREATE TABLE image
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fileSize  INTEGER NOT NULL,
    mediaType TEXT    NOT NULL,
    data      BYTEA   NOT NULL
);

-- changeset Yuri:1

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR NOT NULL,
    last_name  VARCHAR NOT NULL,
    phone      VARCHAR NOT NULL,
    email      VARCHAR NOT NULL,
    password   VARCHAR NOT NULL,
    role       VARCHAR DEFAULT 'USER',
    image_id   BIGINT REFERENCES image (id)
);

-- changeset Max:1

CREATE TABLE ads
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT,
    price       INTEGER,
    title       TEXT,
    user_id     BIGINT REFERENCES users (id),
    image_id    BIGINT REFERENCES image (id)
);

-- changeset Dmitry:1

CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    text       VARCHAR   NOT NULL,
    ads_id     BIGINT REFERENCES ads (id),
    author_id  BIGINT REFERENCES users (id)
);